Enable compiling on Clang and fix warnings about missing `override` specifiers (#22)
* Bugfixes which enable compiling OpenFBX on Clang.

Relevant Clang error messages before fixes:

/OpenFBX/src/ofbx.cpp:1637:35: error: static declaration of 'parseArrayRaw' follows non-static declaration
template <typename T> static bool parseArrayRaw(const Property& property, T* out, int max_size)
                                  ^
/OpenFBX/src/ofbx.cpp:307:28: note: previous declaration is here
template <typename T> bool parseArrayRaw(const Property& property, T* out, int max_size);
                           ^
/OpenFBX/src/ofbx.cpp:1789:35: error: static declaration of 'parseBinaryArray' follows non-static declaration
template <typename T> static bool parseBinaryArray(const Property& property, std::vector<T>* out)
                                  ^
/OpenFBX/src/ofbx.cpp:308:28: note: previous declaration is here
template <typename T> bool parseBinaryArray(const Property& property, std::vector<T>* out);

Tested with clang version 3.8.1-24 (tags/RELEASE_381/final).

	modified:   src/ofbx.cpp

* Add missing `override` specifiers.

Relevant Clang warning messages before fixes:

/OpenFBX/src/ofbx.cpp:1176:9: warning: 'getTransformMatrix' overrides a member function but is not marked 'override'
      [-Winconsistent-missing-override]
        Matrix getTransformMatrix() const { return transform_matrix; }
               ^
/OpenFBX/src/ofbx.h:231:17: note: overridden virtual function is here
        virtual Matrix getTransformMatrix() const = 0;
                       ^
/OpenFBX/src/ofbx.cpp:1177:9: warning: 'getTransformLinkMatrix' overrides a member function but is not marked 'override'
      [-Winconsistent-missing-override]
        Matrix getTransformLinkMatrix() const { return transform_link_matrix; }
               ^
/OpenFBX/src/ofbx.h:232:17: note: overridden virtual function is here
        virtual Matrix getTransformLinkMatrix() const = 0;
                       ^
/OpenFBX/src/ofbx.cpp:1268:24: warning: 'getLayer' overrides a member function but is not marked 'override'
      [-Winconsistent-missing-override]
        const AnimationLayer* getLayer(int index) const
                              ^
/OpenFBX/src/ofbx.h:294:32: note: overridden virtual function is here
        virtual const AnimationLayer* getLayer(int index) const = 0;
                                      ^
/OpenFBX/src/ofbx.cpp:1375:6: warning: 'getAnimationStackCount' overrides a member function but is not marked 'override'
      [-Winconsistent-missing-override]
        int getAnimationStackCount() const { return (int)m_animation_stacks.size(); }
            ^
/OpenFBX/src/ofbx.h:349:14: note: overridden virtual function is here
        virtual int getAnimationStackCount() const = 0;

Tested with clang version 3.8.1-24 (tags/RELEASE_381/final).

	modified:   src/ofbx.cpp